[tool.poetry]
name = "adventofcode2021"
version = "0.1.0"
description = "Advent of Code 2021 implementations"
authors = ["hckr"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
